# Generated by Django 2.0.9 on 2018-10-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discografica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='author',
            new_name='autor',
        ),
    ]
