# Generated by Django 2.0.9 on 2018-11-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discografica', '0002_auto_20181031_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='portada',
        ),
    ]
